### ISSUE TITLE
'sqlb-openssl@3' formula conflicts with Homebrew official 'openssl@3' formula

### ISSUE THREAD

**Issue by lucydodo** [sqlitebrowser/homebrew-tap#1]
E.O.M.

**Comment by justinclift** [comment]
If that meaning a path conflict during installation, or is it more the wrong installation of SQLite 3 on a system is being used during build(s)?

**Comment by lucydodo** [comment]
No, what I meant was that the symlinks conflict. However, I think I've found a solution and will test it in a bit. :)

**Comment by lucydodo** [comment]
Well, I tested it and it doesn't work as intented. Let's take another look at it after we finish the release the next version :)
